/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTaskIndexRouteImport } from './routes/app/task/index'
import { Route as AppTaskAddRouteImport } from './routes/app/task/add'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTaskIndexRoute = AppTaskIndexRouteImport.update({
  id: '/app/task/',
  path: '/app/task/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTaskAddRoute = AppTaskAddRouteImport.update({
  id: '/app/task/add',
  path: '/app/task/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/task/add': typeof AppTaskAddRoute
  '/app/task/': typeof AppTaskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/task/add': typeof AppTaskAddRoute
  '/app/task': typeof AppTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/task/add': typeof AppTaskAddRoute
  '/app/task/': typeof AppTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/$' | '/app/task/add' | '/app/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/app/task/add' | '/app/task'
  id: '__root__' | '/' | '/api/auth/$' | '/app/task/add' | '/app/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppTaskAddRoute: typeof AppTaskAddRoute
  AppTaskIndexRoute: typeof AppTaskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/task/': {
      id: '/app/task/'
      path: '/app/task'
      fullPath: '/app/task/'
      preLoaderRoute: typeof AppTaskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/task/add': {
      id: '/app/task/add'
      path: '/app/task/add'
      fullPath: '/app/task/add'
      preLoaderRoute: typeof AppTaskAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppTaskAddRoute: AppTaskAddRoute,
  AppTaskIndexRoute: AppTaskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
